### ISSUE TITLE
API Design for receiving data from vehicle

### ISSUE THREAD

**Issue by alldne** [gcivil-nyu-org/spring2020-cs-gy-9223-class#12]
**User story**
As backend team member, I want an API to receive data from vehicle so that h/w team can send data through the API
 
**Acceptance criteria**
- API (hopefully RESTFul) **document** in the wiki
- We don't have to consider radio at this point because h/w team will provide us a script that running on our machine and we can use them to send data to the same API

**Definition of Done**
I know this is done I can see a document in the github wiki describing API to receive sensor data from vehicle

**Comment by Ziheng-Wang** [comment]
https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/wiki/RadioReceiver-API-documentation

**Comment by Ziheng-Wang** [comment]
Some material for learning Django REST framework is below : 
[https://www.django-rest-framework.org/](url)
[https://www.django-rest-framework.org/tutorial/quickstart/](url)
