### ISSUE TITLE
Update Data Model Wiki page

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#122]
**User story**
The current [wiki page](https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/wiki/Database-Schema) is not up-to-date with the finalized database schema.

**Acceptance criteria**
- Diagram is updated and correct.
- Wiki includes documentation of the database schema:
    - Tables, fields, relationships
    - How to work with the database

**Definition of Done**
The wiki page for database schema is up to date and complete.

**Comment by Ziheng-Wang** [comment]
![database model diagram](https://user-images.githubusercontent.com/59923559/76714840-bd7cfc80-66ff-11ea-8176-b4f051366552.png)

**Comment by jackxujh** [comment]
@Ziheng-Wang thanks for the new wiki page revision! There is just one thing I think may be puzzling for outside users, which is, the field names do not 100% match those in the data model. Would you think it would be a good idea to keep them exactly the same?

**Comment by Ziheng-Wang** [comment]
> @Ziheng-Wang thanks for the new wiki page revision! There is just one thing I think may be puzzling for outside users, which is, the field names do not 100% match those in the data model. Would you think it would be a good idea to keep them exactly the same?

Yes, I was thinking the same way as you, but you know the uuid in model means nothing, why I name it sensor_id or event_id is to make it more intuitive and it's easy to understood by user.

**Comment by jackxujh** [comment]
@Ziheng-Wang I think people will get the idea if we list the field as `id` or `uuid` in the graph. It feels to me personally, though, I would expect the graph to *accurately* reflect the schema. But I am okay with the way it is right now. 

On another note, we should use one (1) unified naming fashion. So `Venue.name` and `Sensor.sensor_name` do not show up in the same diagram; nor do both snake case and camel case, like `sensorType_name`. Just trying to help – because I did the same thing before 😁

**Comment by Ziheng-Wang** [comment]
> @Ziheng-Wang I think people will get the idea if we list the field as `id` or `uuid` in the graph. It feels to me personally, though, I would expect the graph to _accurately_ reflect the schema. But I am okay with the way it is right now.
> 
> On another note, we should use one (1) unified naming fashion. So `Venue.name` and `Sensor.sensor_name` do not show up in the same diagram; nor do both snake case and camel case, like `sensorType_name`. Just trying to help – because I did the same thing before 😁

Okay, I will fix it, thanks for pointing out.
