### ISSUE TITLE
Tech Story:  Deploying SymmetricDs by following the documentation strictly 

### ISSUE THREAD

**Issue by iamvibhorsingh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#123]
**Acceptance criteria**

SymmetricDs does synchronization exactly how it shows in the documentation.

https://www.symmetricds.org/doc/3.11/html/tutorials.html

**Definition of Done**
I know this is done when  symmetricDs works as shown in documentation

**Comment by alldne** [comment]
I followed through their doc and it worked as expected.
