### ISSUE TITLE
Tech Story: Write a simulator script for data sender

### ISSUE THREAD

**Issue by alldne** [gcivil-nyu-org/spring2020-cs-gy-9223-class#13]
**User story**
As backend team member, I want a simulator script for data sender so that in the future, I can test our API without real data incoming from vehicle.

**Acceptance criteria**
- A script that calls our API from https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/issues/12 with fake data
- Shell script or python are strongly recommended so that our team members can easily understand it.
- It should be able to be run on any of the following OS: macOS, Windows, Linux.
- A short document about how to use it

**Definition of Done**
I know this is done when I have a program that can sends fake sensor data to our API and have a documentation on it.

**Comment by jackxujh** [comment]
I worked on some of the API implementation last week, and then realized it was too early. However, I think the *serializers* (which are partially functioning) could be a starting point when we actually implement the feature: #76 .
