### ISSUE TITLE
Tech Story: Clear development process

### ISSUE THREAD

**Issue by alldne** [gcivil-nyu-org/spring2020-cs-gy-9223-class#14]
**Acceptance criteria**
Document including:
- how to pull changes from upstream to team branch
- how to create a PR from team branch to upstream
- how to maintain team branch
- how to merge each team member's changes in to the team branch
- review / commit message guideline

**Comment by VentusXu09** [comment]
https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/wiki/Backend-Team-Development-Process
