### ISSUE TITLE
Integrate sprint progress and demo rehearsal

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#180]
**User story**
As the user, I want to see the whole data flow works in the sprint demo, from sending data from the simulator to the data storage, to seeing that data stored and synced to another end client.

**Acceptance criteria**
The demo runs as follows:
- Receive measurements from a radio receiver
- Receive measurements from the Internet
- Process measurements with predefined formulas based on the sensor type
- Store measurements with both raw data and result
- Sync measurements between databases using SymDS, with conflict resolving
- Show synced measurements on all end clients

**Definition of Done**
The demo is rehearsed with predefined sequence, and the rehearsal is successful.

**Comment by jackxujh** [comment]
also we will show the new setup script.

**Comment by alldne** [comment]
Let me close this issue because it's outdated
