### ISSUE TITLE
Synchronization configuration script for SymDs (for unix-like OS)

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#188]
### User Story
The user wants the synchronization to be working once they install and initialize the program. SymmetricDS will also need to be properly configured during the project initialization. This user story allows the SymmetricDS setup to be automated, so users won't worry about it.

### Acceptance Criteria

The script include:

- Copy `*properties` files
- Check the postgres configuration (pg_hba.conf, etc.)
- Check the basic connection between local postgres and symmetricds
- Create relevant tables and initial data in the database
- The configuration should be worked with the current model
- And...

### Definition of Done
This script is finished and merged into the repository. Members within the backend team can use this to set up SymDS on their computer (as internal tests).

**Comment by alldne** [comment]
@Ricardo-1894 I pushed some changes. You can run `make configure` under `symmetricds` directory to install & copy template `properties` files.
https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/tree/backend/symd-configuration
