### ISSUE TITLE
Updating UI of Edit Sensor Types

### ISSUE THREAD

**Issue by dandipietrantonio** [gcivil-nyu-org/spring2020-cs-gy-9223-class#192]
**User story**
As a user, I want the UI to be consistent across the app so that I can easily interact with the UI.

**Acceptance criteria**
The "View Sensor Types" page now has an "edit" button for each type. When this button is clicked, the sensor type should be editable in the same way it currently is in the "Edit Sensor Types" tab.

**Definition of Done**
The "Edit Sensor Types" tab is deleted and its functionality is replaced by adding the "Edit Sensor" button straight into the UI of the "View Sensor Types" page.

**Comment by Ray310** [comment]
Edit sensor types view has been removed
