### ISSUE TITLE
Updating UI of Edit Sensors

### ISSUE THREAD

**Issue by dandipietrantonio** [gcivil-nyu-org/spring2020-cs-gy-9223-class#193]
**User story**
As a user, I want the UI to be consistent across the app so that I can easily interact with the UI.

**Acceptance criteria**
The "View Sensor" page now has an "edit" button for each sensor. When this button is clicked, the sensor should be editable in the same way it currently is in the "Edit Sensor" tab.

**Definition of Done**
The "Edit Sensor" tab is deleted and its functionality is replaced by adding the "Edit Sensor" button straight into the UI of the "View Sensor" page.

**Comment by Ray310** [comment]
Updated
