### ISSUE TITLE
How to test hardware related scripts within our repo

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/spring2020-cs-gy-9223-class#20]
How will we test the code/firmware stored in the repo?

this includes figuring out how to run multiple multiple jobs for django and the hardware on travis, as well as virtualizing a pi on travis so that we can run tests against it.

**Comment by ab7289** [comment]
This article (https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages) seems to have promise for running separate travis jobs for the python stuff and the RPi stuff.

**Comment by ab7289** [comment]
This also seems useful for running tests against RPi on Travis.
