### ISSUE TITLE
Opening "Add New Sensor" in new tab results in bad view

### ISSUE THREAD

**Issue by Ray310** [gcivil-nyu-org/spring2020-cs-gy-9223-class#240]
## Expected Behavior
Opening "Configure Sensors" in new tab should result in same view as clicking on sidebar

## Current Behavior
Opening in new tab shows the views as if all buttons were engaged

**Comment by dandipietrantonio** [comment]
I fixed this yesterday, it should be in frontend-team and master. Please pull from frontend-team and let me know if it still happens.
