### ISSUE TITLE
CommPi Automatically Forwards LAN Messages to Internet and Radio

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/spring2020-cs-gy-9223-class#279]
**User story**
As user, I want my CommPi to automatically send any messages that it receives over LAN to the application using both the serial port Radio and connected Wifi network so that data can be effectively transmitted off of the vehicle.

**Acceptance criteria**
CommPi should, on boot, connect to its LAN / Ethernet connection and begin receiving messages. It should also automatically connect to its wifi network and locate the serial port of the radio module. It should then be able to send its incoming messages over the internet and over the radio.

**Definition of Done**
Script with this functionality is pushed and merged to the hardware branch.

**Comment by ab7289** [comment]
PR'ed into master
