### ISSUE TITLE
Message Sensor Data between Boards via LAN

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/spring2020-cs-gy-9223-class#31]
**User story**
As developer, I want to message sensor data between boards to demonstrate that live sensor data can be received on a board that was not the original source of the data.

**Acceptance criteria**
This messaging is to be done over LAN ethernet and messages should be in JSON format.

**Definition of Done**
Live data from the Sense Hat, in on-vehicle messaging protocol, should be displayed on the screen or terminal of the Pi to which the Sense Hat is not attached.

**Comment by ab7289** [comment]
merged to master
