### ISSUE TITLE
Find/Refactor code

### ISSUE THREAD

**Issue by daisycrego** [gcivil-nyu-org/spring2020-cs-gy-9223-class#345]
This is for the Class 11 Assignment.

Find an example of “bad” code
- Write tests to ensure its behavior
- Refactor code
- Validate its correctness through those tests
- Prepare presentation for next class on:
- What the bad code was
- Why it had to go
- What the new code is
- Why the new code is better
- How the tests prove that the new code still works

**User story**

**Acceptance criteria**

**Definition of Done**

**Comment by Ray310** [comment]
Discussed refactor of add/edit sensors
