### ISSUE TITLE
Figure out timestamp issue

### ISSUE THREAD

**Issue by daisycrego** [gcivil-nyu-org/spring2020-cs-gy-9223-class#346]
Time data is being stored/transmitted in an incorrect format, and isn't being detected properly by Grafana. 

**User story**

**Acceptance criteria**

**Definition of Done**

**Comment by jackxujh** [comment]
My intuition is, the way our measurement API stores the timestamp is different from the way the simulator generates and saves the timestamp. So Grafana can recognize simulated measurements, but not actual measurements from the hardware. The backend team will try to use some testing to analyze if it this is part of the reason.

**Comment by jackxujh** [comment]
The issue has been resolved.
