### ISSUE TITLE
Add examples of JSON for the database schema wiki page

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#352]
**User story**
There are confusions on the JSON format. And there is a need to have a wiki on how it works.

**Acceptance criteria**
- An updated wiki page for our JSON formats in the database schema.
- The information on the topic is accurate and up-to-date.
- Other teams can view and understand the format.

**Definition of Done**

**Comment by Ziheng-Wang** [comment]
https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/wiki/Database-Schema

**Comment by jackxujh** [comment]
@Ziheng-Wang could you add some example JSON to illustrate the point? Like this other wiki page: https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/wiki/RadioReceiver-API-documentation

**Comment by Ziheng-Wang** [comment]
> @Ziheng-Wang could you add some example JSON to illustrate the point? Like this other wiki page: https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/wiki/RadioReceiver-API-documentation

Okay, that make sense, will do.
