### ISSUE TITLE
As a backend team member, he/she should set up Heroku instance.

### ISSUE THREAD

**Issue by Ricardo-1894** [gcivil-nyu-org/spring2020-cs-gy-9223-class#354]
**User story**
Every team member in the backend team should have Heroku instance setup.

**Acceptance criteria**
* Heroku instance is setup and work correctly

**Definition of Done**
* Every backend team member finish this user story

**Comment by iamvibhorsingh** [comment]
My instance `http://vibhorinstance.herokuapp.com/`
