### ISSUE TITLE
More descriptive errors for invalid requests

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#355]
**User story**
The API now responds with a blunt 500 code when the received data is invalid. The user of the API would like to have more descriptive and helpful information when they receive the error.

**Acceptance criteria**
- The API responds with appropriate message when known type of errors are triggered.
    - extra fields
    - incorrect formats
    - missing fields
    - and...
- tests handle these situations

**Definition of Done**
The change is done, tested and merged.

**Comment by alldne** [comment]
https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/pull/388

**Comment by alldne** [comment]
https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/pull/388
