### ISSUE TITLE
Transmit Sensor Data via Internet

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/spring2020-cs-gy-9223-class#38]
**User story**
As developer, I want to be able to transmit properly-formatted sensor data from the Sense Hat off of the vehicle via radio so that accurate sensor data can be received by the locally hosted application.

**Acceptance criteria**
This story combines several hardware pieces and demonstrates an ability to:
- Read data from Sense Hat
- Convert data to on-vehicle format
- Message data from one board to another board in on-vehicle format
- Receive message and convert it to database-friendly, off-vehicle format
- Transmit the data via internet adapter

**Definition of Done**
Live sensor data can be received and displayed by a laptop/server that is open to receiving these messages.

**Comment by ab7289** [comment]
PR'ed into master
