### ISSUE TITLE
Remove schema_demo/

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#401]
**User story**
This demo version of the schema is no longer used, and should be removed from the repo to avoid confusion.

**Acceptance criteria**
- the code in this folder is checked and removed
- necessary code is refactored or replaced to another folder
- the empty folder schema_demo/ is deleted
- tests are updated so the outcome is a working repo

**Definition of Done**
changes are finished, tested, and merged to team branch

**Comment by alldne** [comment]
https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/pull/443
