### ISSUE TITLE
Convert SensePi Scripts to Modules 

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/spring2020-cs-gy-9223-class#412]
**User story**
As developer and user, I want the code that controls use of the SensePi to be modularized so that it can be tested and easily invoked.

**Acceptance criteria**
Current code in the hardware/SensePi directory should be converted into a module that can be imported in a main control file or script. (creating that main file is outside the scope of this user story)

**Definition of Done**
Module has be created and pushed to the hardware branch.

**Comment by ab7289** [comment]
merged to master
