### ISSUE TITLE
Main hardware control script

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/spring2020-cs-gy-9223-class#413]
**User story**
As user and developer, I want a main control script that carries the functionality of each type of Pi and does so by responding to environment variables and invoking modules so that the actions of a Pi can be centrally located, understood, and modified as needed.

**Acceptance criteria**
A file "main.py" should be created in the hardware/ directory. It should import the available sensor and communication modules and should use references to environment variables to determine its functionality.

**Definition of Done**
This main.py file has been created and has been pushed to the hardware branch

**Comment by ab7289** [comment]
merged to master
