### ISSUE TITLE
Table for error logs

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#444]
**User story**
The user wanted the system to still be able to store a measurement in a separate table if it was a wrong format/invalid one.

**Acceptance criteria**
- **PR to backend-team should be sent by Friday**
- a new table with following columns:
    - timestamp
    - error code: an [option field](https://docs.djangoproject.com/en/3.0/ref/models/fields/#choices) that is predefined to match error
    - error description: string that shows more detail of the error
    - original request: a string value of the raw data

An example row:
```
(
    2020-04-16 09:49:27.425963-04, 
    'unknwon_sensor_id', 
    "100", 
    '{"date":"2020-04-15 02:25:13.880456","sensor_id":"100","values": {"temperature":"35.56126022338867"}}' 
)
```

Error code:

- unrecognized format (auxiliary: unrecognized content)
- missing column (auxiliary: which column)
- column invalid (auxiliary: column content)
- missing field in raw reading (auxiliary: first missing field)
- field in raw reading invalid (auxiliary: first invalid field)
- error when processing measurement in the formula (auxiliary: formula name and arguments used)
- extraneous key-value pair in measurement received by API (auxiliary: first exraneous pair)
- other error (auxiliary: error)

**Definition of Done**
I know this is done when we have the added data model in the project, with tests, and is merged into master.

**Comment by Ricardo-1894** [comment]
https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/pull/491
