### ISSUE TITLE
The API and pipeline is able to log errors using the new log table

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#446]
**User story**
Currently, all API and pipeline don't deal much with error. API and pipeline should be able to record errors when they are running.

**Acceptance criteria**
- Deadline: PR should be created by Monday
- API and pipeline record error when throwing an exception.

**Definition of Done**
I know this is done when we have the added error recording in API and pipeline in the project, with tests, and is merged into master.

**Comment by Ricardo-1894** [comment]
https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/pull/604
