### ISSUE TITLE
Use singleton model for active event

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#447]
**User story**
The current implementation of active event model may cause several rows in the database, and is not easy to maintain. Using singleton design will help resolve this situation.

Useful links:
- [Singleton Design Pattern Example_ Singleton Models in Django](https://steelkiwi.com/blog/practical-application-singleton-design-pattern/)

**Acceptance criteria**
- the ActiveEvent model is a singleton model.
- tests are updated.

**Definition of Done**
I know this is done when the feature is completed, tested and merged to master.

**Comment by Ziheng-Wang** [comment]
https://goodcode.io/articles/django-singleton-models/

**Comment by Ziheng-Wang** [comment]
https://gist.github.com/senko/5028413 I found this example of code is useful. Based on his code, what we need to be clear is that if we need to notify user there is already a event in table or we just overwrite the table.

**Comment by jackxujh** [comment]
I think there are two parts to this. The first is to declare an abstract model with possible name like `SingletonModel`, then declare the `AGActiveEvent` model as a subclass that inherits this abstract model.

**Comment by jackxujh** [comment]
@Ziheng-Wang I am not exactly sure what do you mean about notifying the user about the active event. The UI has a toggle. You can see it if you run `master` code.

**Comment by Ziheng-Wang** [comment]
> @Ziheng-Wang I am not exactly sure what do you mean about notifying the user about the active event. The UI has a toggle. You can see it if you run `master` code.

**Comment by Ziheng-Wang** [comment]
Singleton model usually used to design a table which constantly have one instance (one row) since this class is loaded.
