### ISSUE TITLE
Handle 415 status in Measurement API

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#644]
**User story**
The API will reject requests that have Content Type other than `application/json`. It returns a 415 status code. But this is an unknown behavior from the code, and it is not mentioned in the instruction as a requirement to use the API. It can be puzzling for users.

**Acceptance criteria**
- Use API utilities to send and check the API. Report which content types are support and not supported.
- Check if it is Django or project code rejecting requests and return 415.
- Provide solution, including documentation or code change, based on the cause of the issue.
- Add tests to guard the behavior.

**Definition of Done**
The 415 status code to return to the user agent is now a known behavior.

**Comment by Ziheng-Wang** [comment]
https://httpstatuses.com/415

**Comment by alldne** [comment]
Changes on the api documentation would be enough?

**Comment by jackxujh** [comment]
@alldne i think it would be enough for the user. But still, [the code we have](https://github.com/gcivil-nyu-org/spring2020-cs-gy-9223-class/blob/master/mercury/views/measurement.py) does not suggest we are limiting the POST request to `application/json`. I hope this user story can have a little digging and reveal why the limitation is added.

**Comment by jackxujh** [comment]
The measurement API always surprises us _every week_ during rehearsal. I would say, it is either the user does not get the idea of this API, or the API has not been designed to be easy to work with. But either case, we want to make the life easier for the user as best as we can.
