### ISSUE TITLE
Add support for macOS (osx) in Travis CI

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#646]
**User story**
Add macOS worker configuration in Travis CI.

**Acceptance criteria**
- The macOS worker will work on Travis.
- Dependencies are configured properly.
- Project's tests run on the macOS worker, and can pass.
- Existing workers should still function, and existing tests pass when run on these workers.

**Definition of Done**
The code is finished, reviewed and merged to master.

**Comment by VentusXu09** [comment]
Kamino cloned this issue to [mercury-telemetry/mercury](https://github.com/mercury-telemetry/mercury/issues/1)

**Comment by VentusXu09** [comment]
Kamino cloned this issue to [mercury-telemetry/mercury-test](https://github.com/mercury-telemetry/mercury-test/issues/136)
