### ISSUE TITLE
Uncaught code format errors in hardware app

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#73]
The new Python module in the `hardware` app does not have tests or code formatting checks which will execute in Travis CI. While the pull request passed CI and was merged to `master`, under some circumstances, code checks emit warnings.

## Expected Behavior
The new app (`hardware`) is expected to have tested and checked with code formatting (`black` and `flake8`) and 100% passed, before merging to master. So the master branch is clean, and when other contributors work on the project, they don't need to worry about errors or warnings that can potentially crash the project or fail CI.

## Current Behavior

- Tests and checks are not configured to perform on the module.
- The code in `master` triggers warnings in `flake8` checks.

## Ideas for Improvement
Update _Travis commands_, and the _check script_.

## Steps to Reproduce
1. Check out the version with pull request #65 and navigate to the project root directory.
2. use the flake8 command as follows to reveal any issue in the hardware app.

```
flake8 hardware
```

3. the following output shows certain files do not comply with default code check rules.

```
/hardware/CommunicationsPi/port.py:55:5: F841 local variable 'res' is assigned to but never used
/hardware/CommunicationsPi/port.py:57:5: F841 local variable 'ss_id' is assigned to but never used
/hardware/CommunicationsPi/port.py:58:5: F841 local variable 'ss_value' is assigned to but never used
/hardware/CommunicationsPi/port.py:59:5: F841 local variable 'date' is assigned to but never used
/hardware/CommunicationsPi/serial_read.py:17:8: F632 use ==/!= to compare str, bytes, and int literals
```

**Comment by ab7289** [comment]
closed and merged to master
